# Main helmfile - references all service helmfiles
helmDefaults:
  atomic: false
  wait: true
  timeout: 10m

helmfiles:
  - path: secrets-chart/helmfile.yaml

  - path: postgres/helmfile.yaml

  - path: authentik/helmfile.yaml

  - path: vaultwarden/helmfile.yaml

  # - path: bitwarden/helmfile.yaml
  # - path: immich/helmfile.yaml
