persistence:
  storageClass: local-nas
  size: 50Gi

postgresql:
  enabled: false

authentik:
  postgresql:
    host: postgres.database.svc.cluster.local
    port: 5432
    name: authentik
    user: authentik
    password:
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: authentikPassword

server:
  ingress:
    enabled: true
    hosts:
      - host: "auth.hestia"
        paths: ["/"]
    tls:
      - secretName: auth-tls
        hosts:
          - "auth.hestia"
