enableRbac: true

env:
  - name: LOG_TARGETS
    value: "stdout"
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "homepage.home.ey-timo-ey.de"

ingress:
  main:
    enabled: true
    className: "traefik"
    hosts:
      - host: "homepage.home.ey-timo-ey.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: homepage-tls
        hosts:
          - "homepage.home.ey-timo-ey.de"
