{{- range $name, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $secret.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
